### ISSUE TITLE
Package doesn't work when it's compiled with pyinstaller

### ISSUE THREAD

**Issue by Thoosje** [MrLucasCardoso/pycards#1]
My script works perfect when it isn't compiled. But once I compile it into an exe with pyinstaller and pyarmour I always get this error:

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "site-packages\pycards\cards\card.py", line 42, in _load_data_file
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\test\\AppData\\Local\\Temp\\_MEI20282\\pycards/data.json'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "<frozen Main.main>", line 540, in main
  File "<frozen main.main>", line 403, in postPayment
  File "site-packages\pycards\cards\card.py", line 126, in brand
  File "site-packages\pycards\cards\card.py", line 140, in data
  File "site-packages\pycards\cards\card.py", line 50, in _load_data
  File "site-packages\pycards\cards\card.py", line 45, in _load_data_file
pycards.cards.card.NoDatabaseExist: File data.json in incorrect format.

Is it possible to fix this?

**Comment by mrlucascardoso** [comment]
Yes

**Comment by Thoosje** [comment]
> Yes

Already fixed it, thx!
